version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "13500:8000"
    volumes:
      - "./api/api:/app/api"
    env_file: api/settings.env
