version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    expose:
      - "13500"
    ports:
      - "13500:13500"
    env_file: settings.env

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      